# config/app.yml for rails-settings-cached
defaults: &defaults
  phone: ''
  email: ''
  landing_form_recipients: ''
  currency_symbol: 'Â£'
  linkedin: ''
  twitter: ''
  google_play: ''
  app_store: ''
  google_static_maps_key: ''
  privacy_policy_text: ''
  primary_site_url: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
